# Generated by Django 5.1.6 on 2025-04-26 12:38

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSitins',
            fields=[
            ],
            options={
                'verbose_name': 'Search Student',
                'verbose_name_plural': 'Search Students',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Sitin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, choices=[('Java Programming', 'Java Programming'), ('C# Programming', 'C# Programming'), ('Systems Integration & Architecture', 'Systems Integration & Architecture'), ('Embedded Systems & IoT', 'Embedded Systems & IoT'), ('Digital Logic & Design', 'Digital Logic & Design'), ('Computer Application', 'Computer Application'), ('Database', 'Database'), ('Project Management', 'Project Management'), ('Python Programming', 'Python Programming'), ('Mobile Application', 'Mobile Application'), ('Web Design', 'Web Design'), ('Php Programming', 'Php Programming'), ('Others', 'Others')], max_length=255, null=True)),
                ('programming_language', models.CharField(blank=True, choices=[('Python', 'Python'), ('Java', 'Java'), ('C', 'C'), ('C++', 'C++'), ('C#', 'C#'), ('JavaScript', 'JavaScript'), ('PHP', 'PHP'), ('HTML & CSS', 'HTML & CSS'), ('SQL', 'SQL'), ('Ruby', 'Ruby'), ('Go', 'Go'), ('Swift', 'Swift'), ('Kotlin', 'Kotlin')], max_length=255, null=True)),
                ('lab_room', models.CharField(blank=True, choices=[('524', 'Room 524'), ('526', 'Room 526'), ('528', 'Room 528'), ('530', 'Room 530'), ('542', 'Room 542'), ('544', 'Room 544'), ('517', 'Room 517')], max_length=50, null=True)),
                ('sitin_details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('none', 'Not Sitin'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('finished', 'Finished')], default='none', max_length=50)),
                ('sitin_date', models.DateTimeField(auto_now_add=True)),
                ('logout_date', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AllSitins',
            fields=[
            ],
            options={
                'verbose_name': 'All Sitin',
                'verbose_name_plural': 'All Sitins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sitins.sitin',),
        ),
        migrations.CreateModel(
            name='CurrentSitins',
            fields=[
            ],
            options={
                'verbose_name': 'Current Sit-in',
                'verbose_name_plural': 'Current Sit-ins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sitins.sitin',),
        ),
        migrations.CreateModel(
            name='FeedbackReport',
            fields=[
            ],
            options={
                'verbose_name': 'Feedback Report',
                'verbose_name_plural': 'Feedback Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sitins.sitin',),
        ),
        migrations.CreateModel(
            name='FinishedSitins',
            fields=[
            ],
            options={
                'verbose_name': 'Sit-in History',
                'verbose_name_plural': 'Sit-ins History',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sitins.sitin',),
        ),
    ]
