# Generated by Django 5.1.6 on 2025-04-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitins', '0002_delete_feedbackreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitin',
            name='request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitin',
            name='sitin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
