# Generated by Django 5.1.6 on 2025-05-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitins', '0003_sitin_request_date_alter_sitin_sitin_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitin',
            name='is_rewarded',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
