# Generated by Django 5.1.6 on 2025-05-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitins', '0004_sitin_is_rewarded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allsitins',
            options={'verbose_name': 'All sitins', 'verbose_name_plural': 'All sitins'},
        ),
        migrations.AlterModelOptions(
            name='currentsitins',
            options={'verbose_name': 'Currently sit-in', 'verbose_name_plural': 'Currently sit-ins'},
        ),
        migrations.AlterModelOptions(
            name='finishedsitins',
            options={'verbose_name': 'Sit-in history', 'verbose_name_plural': 'Sit-in history'},
        ),
        migrations.AlterModelOptions(
            name='searchsitins',
            options={'verbose_name': 'Search student to sitin', 'verbose_name_plural': 'Search student to sitin'},
        ),
    ]
