# Generated by Django 5.1.6 on 2025-05-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitins', '0005_alter_allsitins_options_alter_currentsitins_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitin',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
