# Generated by Django 5.1.6 on 2025-04-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_sitinrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitinrequest',
            name='user',
        ),
    ]
