# Generated by Django 5.1.6 on 2025-04-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_remove_sitinrequest_user'),
        ('sitins', '0003_sitin_request_date_alter_sitin_sitin_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SitinRequests',
        ),
        migrations.CreateModel(
            name='SitinRequestsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Sit-in Request',
                'verbose_name_plural': 'Sit-in Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sitins.sitin',),
        ),
    ]
