# Generated by Django 5.1.6 on 2025-05-03 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_delete_sitinrequests_sitinrequestsproxy'),
        ('sitins', '0004_sitin_is_rewarded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SitinRequestsProxy',
        ),
        migrations.CreateModel(
            name='ReservationLogProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Reservation log',
                'verbose_name_plural': 'Reservation logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sitins.sitin',),
        ),
        migrations.CreateModel(
            name='ReservationRequestProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Reservation request',
                'verbose_name_plural': 'Reservation requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sitins.sitin',),
        ),
    ]
