# Generated by Django 5.1.5 on 2025-01-31 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=80)),
                ('firstname', models.CharField(max_length=80)),
                ('middlename', models.CharField(max_length=80)),
                ('case', models.IntegerField()),
                ('level', models.IntegerField()),
                ('email', models.EmailField(max_length=80)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
