# Generated by Django 5.1.6 on 2025-02-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_registration_case_registration_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.CharField(default='Cebu City', max_length=255),
            preserve_default=False,
        ),
    ]
