# Generated by Django 5.1.6 on 2025-02-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_registration_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='sessions',
            field=models.IntegerField(default=30),
        ),
    ]
