# Generated by Django 5.1.6 on 2025-02-24 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_announcement_content_alter_announcement_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementcomment',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='backend.announcement'),
        ),
    ]
