# Generated by Django 5.1.6 on 2025-02-24 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_announcementcomment_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementcomment',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.announcement'),
        ),
    ]
