# Generated by Django 5.1.6 on 2025-02-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_announcementcomment_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, default='announcements/announcement.jpg', null=True, upload_to='announcements/'),
        ),
    ]
