# Generated by Django 5.1.6 on 2025-02-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_sitin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitin',
            name='sitin_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
