# Generated by Django 5.1.6 on 2025-02-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_sitin_sitin_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitin',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
