# Generated by Django 5.1.6 on 2025-03-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_sitin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitin',
            name='lab_room',
            field=models.CharField(blank=True, choices=[('524', 'Room 524'), ('526', 'Room 526'), ('527', 'Room 527'), ('528', 'Room 528'), ('529', 'Room 529'), ('530', 'Room 530'), ('544', 'Room 544'), ('546', 'Room 546')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitin',
            name='programming_language',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('Java', 'Java'), ('C', 'C'), ('C++', 'C++'), ('C#', 'C#'), ('JavaScript', 'JavaScript'), ('PHP', 'PHP'), ('HTML & CSS', 'HTML & CSS'), ('SQL', 'SQL'), ('Ruby', 'Ruby'), ('Go', 'Go'), ('Swift', 'Swift'), ('Kotlin', 'Kotlin')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitin',
            name='purpose',
            field=models.CharField(blank=True, choices=[('class', 'Attending a Class'), ('project', 'Working on a Project'), ('exam', 'Taking an Exam'), ('research', 'Conducting Research'), ('training', 'Skill Training / Workshop'), ('software_testing', 'Software Testing'), ('network_configuration', 'Network Configuration'), ('data_analysis', 'Data Analysis'), ('web_development', 'Web Development'), ('game_development', 'Game Development'), ('ai_ml', 'Artificial Intelligence / Machine Learning'), ('database_management', 'Database Management'), ('cybersecurity', 'Cybersecurity Practice'), ('assignment', 'Completing an Assignment')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitin',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=50, null=True),
        ),
    ]
