# Generated by Django 5.1.6 on 2025-03-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_sitin_lab_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='course',
            field=models.CharField(blank=True, choices=[('BSIT', 'Bachelor of Science in Information Technology'), ('BSCS', 'Bachelor of Science in Computer Science'), ('BSCPE', 'Bachelor of Science in Computer Engineering'), ('BSIS', 'Bachelor of Science in Information Systems'), ('BSCE', 'Bachelor of Science in Civil Engineering'), ('BSEE', 'Bachelor of Science in Electrical Engineering'), ('BSECE', 'Bachelor of Science in Electronics and Communications Engineering'), ('BSME', 'Bachelor of Science in Mechanical Engineering'), ('BSBA', 'Bachelor of Science in Business Administration'), ('BSHRM', 'Bachelor of Science in Hospitality and Restaurant Management'), ('BSA', 'Bachelor of Science in Accountancy'), ('BSN', 'Bachelor of Science in Nursing'), ('BSED', 'Bachelor of Secondary Education'), ('BEED', 'Bachelor of Elementary Education'), ('BSP', 'Bachelor of Science in Psychology'), ('BSMT', 'Bachelor of Science in Marine Transportation'), ('BSMarE', 'Bachelor of Science in Marine Engineering'), ('BSTM', 'Bachelor of Science in Tourism Management'), ('BFA', 'Bachelor of Fine Arts'), ('BSArch', 'Bachelor of Science in Architecture'), ('BSPharma', 'Bachelor of Science in Pharmacy')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True),
        ),
        migrations.AlterField(
            model_name='sitin',
            name='purpose',
            field=models.CharField(blank=True, choices=[('Attending a Class', 'Attending a Class'), ('Working on a Project', 'Working on a Project'), ('Taking an Exam', 'Taking an Exam'), ('Conducting Research', 'Conducting Research'), ('Skill Training / Workshop', 'Skill Training / Workshop'), ('Software Testing', 'Software Testing'), ('Network Configuration', 'Network Configuration'), ('Data Analysis', 'Data Analysis'), ('Web Development', 'Web Development'), ('Game Development', 'Game Development'), ('Artificial Intelligence / Machine Learning', 'Artificial Intelligence / Machine Learning'), ('Database Management', 'Database Management'), ('Cybersecurity Practice', 'Cybersecurity Practice'), ('Completing an Assignment', 'Completing an Assignment')], max_length=255, null=True),
        ),
    ]
