# Generated by Django 5.1.6 on 2025-03-07 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_registration_course_alter_registration_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSitins',
            fields=[
            ],
            options={
                'verbose_name': 'Approved Sit-in',
                'verbose_name_plural': 'Approved Sit-ins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.sitin',),
        ),
        migrations.CreateModel(
            name='SitinRequests',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Sit-in',
                'verbose_name_plural': 'Pending Sit-ins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.sitin',),
        ),
    ]
