# Generated by Django 5.1.6 on 2025-03-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_currentsitins_sitinrequests'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedSitins',
            fields=[
            ],
            options={
                'verbose_name': 'Timed-out Sit-in',
                'verbose_name_plural': 'Timed-out Sit-ins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.sitin',),
        ),
        migrations.AlterField(
            model_name='sitin',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('finished', 'Finished')], max_length=50, null=True),
        ),
    ]
