# Generated by Django 5.1.6 on 2025-03-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_finishedsitins_alter_sitin_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentsitins',
            options={'verbose_name': 'Current Sit-in', 'verbose_name_plural': 'Current Sit-ins'},
        ),
        migrations.AddField(
            model_name='sitin',
            name='logout_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
