# Generated by Django 5.1.6 on 2025-03-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_currentsitins_options_sitin_logout_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraSitins',
            fields=[
            ],
            options={
                'verbose_name': 'Sitins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.sitin',),
        ),
    ]
