# Generated by Django 5.1.6 on 2025-03-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_extrasitins'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extrasitins',
            options={},
        ),
    ]
