# Generated by Django 5.1.6 on 2025-03-13 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_alter_extrasitins_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extrasitins',
            options={'verbose_name': 'All Sitin', 'verbose_name_plural': 'All Sitins'},
        ),
    ]
