# Generated by Django 5.1.6 on 2025-03-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_alter_extrasitins_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitin',
            name='sitin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
