# Generated by Django 5.1.6 on 2025-03-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_sitin_sitin_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitin',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
