# Generated by Django 5.1.6 on 2025-03-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_sitin_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitin',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
