# Generated by Django 5.1.6 on 2025-03-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_alter_sitin_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SitinRequests',
        ),
        migrations.AlterModelOptions(
            name='finishedsitins',
            options={'verbose_name': 'View Sit-in History', 'verbose_name_plural': 'View Sit-ins History'},
        ),
        migrations.AlterField(
            model_name='sitin',
            name='status',
            field=models.CharField(blank=True, choices=[('none', 'Not Sitin'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('finished', 'Finished')], max_length=50, null=True),
        ),
    ]
