# Generated by Django 5.1.6 on 2025-03-23 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_delete_sitinrequests_alter_finishedsitins_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraSitins',
        ),
        migrations.CreateModel(
            name='AllSitins',
            fields=[
            ],
            options={
                'verbose_name': 'All Sitin',
                'verbose_name_plural': 'All Sitins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.sitin',),
        ),
        migrations.CreateModel(
            name='SearchSitins',
            fields=[
            ],
            options={
                'verbose_name': 'Search Sit-in',
                'verbose_name_plural': 'Search Sit-ins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.sitin',),
        ),
    ]
