# Generated by Django 5.1.6 on 2025-03-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_delete_extrasitins_allsitins_searchsitins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitin',
            name='status',
            field=models.CharField(choices=[('none', 'Not Sitin'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('finished', 'Finished')], default='none', max_length=50),
        ),
    ]
