# Generated by Django 5.1.6 on 2025-03-23 04:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_delete_userproxy_searchsitins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitin',
            name='date',
        ),
        migrations.AlterField(
            model_name='sitin',
            name='sitin_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
