# Generated by Django 5.1.6 on 2025-03-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_remove_sitin_date_alter_sitin_sitin_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackReport',
            fields=[
            ],
            options={
                'verbose_name': 'Feedback Report',
                'verbose_name_plural': 'Feedback Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.sitin',),
        ),
        migrations.AlterModelOptions(
            name='finishedsitins',
            options={'verbose_name': 'Sit-in History', 'verbose_name_plural': 'Sit-ins History'},
        ),
    ]
