# Generated by Django 5.1.6 on 2025-03-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_remove_sitin_survey_alter_sitinsurvey_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='question',
            field=models.TextField(blank=True, choices=[('How satisfied are you with the overall sit-in process?', 'How satisfied are you with the overall sit-in process?'), ('How easy was it to book a sit-in slot?', 'How easy was it to book a sit-in slot?'), ('Did the system provide clear instructions and requirements for sit-ins?', 'Did the system provide clear instructions and requirements for sit-ins?'), ('How satisfied are you with the response time for sit-in approvals?', 'How satisfied are you with the response time for sit-in approvals?'), ('Would you recommend this system to other students?', 'Would you recommend this system to other students?')], null=True),
        ),
    ]
