# Generated by Django 5.1.6 on 2025-03-29 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_alter_surveyquestion_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.sitinsurvey'),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='question',
            field=models.TextField(blank=True, choices=[(1, 'How satisfied are you with the overall sit-in process?'), (2, 'How easy was it to book a sit-in slot?'), (3, 'Did the system provide clear instructions and requirements for sit-ins?'), (4, 'How satisfied are you with the response time for sit-in approvals?'), (5, 'Would you recommend this system to other students?')], null=True),
        ),
    ]
