# Generated by Django 5.1.6 on 2025-03-29 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_surveyquestion_survey_alter_surveyquestion_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='backend.sitinsurvey'),
        ),
    ]
