# Generated by Django 5.1.6 on 2025-03-29 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_alter_surveyquestion_survey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitinsurvey',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, choices=[(1, 'How satisfied are you with the overall sit-in process?'), (2, 'How easy was it to book a sit-in slot?'), (3, 'Did the system provide clear instructions and requirements for sit-ins?'), (4, 'How satisfied are you with the response time for sit-in approvals?'), (5, 'Would you recommend this system to other students?')], null=True)),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitinsurvey', to='backend.sitinsurvey')),
            ],
        ),
        migrations.DeleteModel(
            name='SurveyQuestion',
        ),
    ]
