# Generated by Django 5.1.6 on 2025-03-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_alter_sitinsurvey_created_by_surveyresponse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='question',
            new_name='question_text',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='question_order',
            field=models.IntegerField(blank=True, choices=[(1, 'How satisfied are you with the overall sit-in process?'), (2, 'How easy was it to book a sit-in slot?'), (3, 'Did the system provide clear instructions and requirements for sit-ins?'), (4, 'How satisfied are you with the response time for sit-in approvals?'), (5, 'Would you recommend this system to other students?')], null=True),
        ),
    ]
