# Generated by Django 5.1.6 on 2025-03-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_alter_sitinsurvey_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='question_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
