# Generated by Django 5.1.6 on 2025-03-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_alter_surveyresponse_question_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
