# Generated by Django 5.1.6 on 2025-03-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0048_alter_surveyresponse_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitinsurvey',
            name='status',
            field=models.CharField(choices=[('not taken', 'Not yet taken'), ('taken', 'Taken')], default='not taken', max_length=50),
        ),
    ]
