# Generated by Django 5.1.6 on 2025-04-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_sitinsurvey_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sitin',
            name='lab_room',
            field=models.CharField(blank=True, choices=[('524', 'Room 524'), ('526', 'Room 526'), ('528', 'Room 528'), ('530', 'Room 530'), ('542', 'Room 542'), ('544', 'Room 544'), ('517', 'Room 517')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitin',
            name='purpose',
            field=models.CharField(blank=True, choices=[('Java Programming', 'Java Programming'), ('C# Programming', 'C# Programming'), ('Systems Integration & Architecture', 'Systems Integration & Architecture'), ('Embedded Systems & IoT', 'Embedded Systems & IoT'), ('Digital Logic & Design', 'Digital Logic & Design'), ('Computer Application', 'Computer Application'), ('Database', 'Database'), ('Project Management', 'Project Management'), ('Python Programming', 'Python Programming'), ('Mobile Application', 'Mobile Application'), ('Web Design', 'Web Design'), ('Php Programming', 'Php Programming'), ('Others', 'Others')], max_length=255, null=True),
        ),
    ]
