# Generated by Django 5.1.6 on 2025-04-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_registration_points_alter_sitin_lab_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='sitins_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
