# Generated by Django 5.1.6 on 2025-04-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_registration_sitins_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresource',
            name='is_enabled',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
