# Generated by Django 5.1.6 on 2025-04-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_remove_labroom_administrated_by_delete_computer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='study_load',
            field=models.FileField(blank=True, null=True, upload_to='schedules/'),
        ),
    ]
