# Generated by Django 5.1.6 on 2025-04-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_registration_study_load'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitin',
            name='user',
        ),
        migrations.DeleteModel(
            name='AllSitins',
        ),
        migrations.DeleteModel(
            name='CurrentSitins',
        ),
        migrations.DeleteModel(
            name='FeedbackReport',
        ),
        migrations.DeleteModel(
            name='FinishedSitins',
        ),
        migrations.DeleteModel(
            name='SearchSitins',
        ),
        migrations.DeleteModel(
            name='Sitin',
        ),
    ]
