# Generated by Django 5.1.6 on 2025-05-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notification_type',
            new_name='badge_type',
        ),
    ]
