# Generated by Django 5.1.5 on 2025-01-31 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='case',
        ),
        migrations.AddField(
            model_name='registration',
            name='course',
            field=models.CharField(default='BSIT', max_length=80),
            preserve_default=False,
        ),
    ]
