# Generated by Django 5.1.6 on 2025-02-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_registration_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='profilepicture',
            field=models.ImageField(blank=True, default='profiles/default.jpg', null=True, upload_to='profiles/'),
        ),
    ]
