# Generated by Django 5.1.6 on 2025-02-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_registration_profilepicture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='profilepicture_og',
            field=models.ImageField(blank=True, default='profiles/default.jpg', null=True, upload_to='profiles/'),
        ),
    ]
